### ISSUE TITLE
The texture change to src/core/node.cpp breaks textureless objects.

### ISSUE THREAD

**Issue by 4onen** [LUGGPublic/CG_Labs#4]
As the title says. Not all OpenGL implementations (possibly even not any?) reset unset uniforms to all zeroes between render calls, so the new has_{texture_name} variables are basically useless. So far I've seen this problem occur on the lab computers and on my Macbook Pro.

_Originally posted by @4onen in https://github.com/LUGGPublic/CG_Labs/commit/eca0cdf6f1ebe725e12b45833012268d2bae67b7#commitcomment-30892214_

Screenshots of issue: https://imgur.com/a/jd8gKHE

To correct this, the only thing I can think of is a global set of texture names, so that the glUniform1i for each texture name can be reset to false on each object. But that's inefficient as heck! 

Perhaps another "fix" could be to warn students of this particular behaviour of OpenGL in advance?

Another option is to remove the has_texture variables entirely, so that any shader program is forced to run with or without textures. This would also necessitate explaining that textures will stick around in the GL_TEXTUREn units, thanks to the state machine, so that people aren't confused by the texture system's behaviour.

Your call, of course.

**Comment by pierremoreau** [comment]
Hello Matthew,

Thanks for the report. The commit above should fix the regression; it simply resets the `has_${texture_name}` to 0 after the rendering all the ones that were defined to 1. I have tested it on assignment 1 by creating a second planet with no texture: without the patch it gets the same texture as the Sun whereas it does not with the patch.

I would rather move away from the state machine, by using the new features from OpenGL 4.5 and beyond, but I don’t think the computers in the lab room would support those new versions (nor students’ laptop, as some use Apple computers which are stuck with OpenGL 4.1, or some other machine that do not support 4.0 and beyond).

**Comment by 4onen** [comment]
That solution makes a lot more sense. I made the mistake of assuming the render call was too far away in the code to do that; should've noticed it was in the same basic block. T.T

I'd like to use OpenGL 4.5+ features as well but, as you say, my laptop's highest OpenGL version is 4.1.

If the course can support the extra setup and learning time, Vulkan does have functionality on most new devices. (Even Macs, through MoltenVK.) If the lab computers are new enough, that might be a good way to go.

Anyway, that's off topic. This commit resolves my issue. Thanks!

**Comment by pierremoreau** [comment]
Thanks for testing. I have pushed the fix to master, along with two other small improvements in the render function as well.

If the hardware does not support OpenGL 4.4 (or 4.5), there is a high chance it won’t be able to support Vulkan either. And the lab computers are not new enough to support it; those are old Fermi cards, released between 2010 and 2012.

If working with Vulkan, we would need to introduce an abstraction layer, as you probably do not want to deal with memory allocation, choosing which type of memory to use, the queuing system, generating all the descriptor layouts and so on, in an introduction course that last seven weeks. Also, almost no one has experience with Vulkan at the department. I have written a simple renderer in Vulkan, but I would not feel confident yet to supervise a Vulkan lab, especially when students could produce any kind of weird bugs.

So, Vulkan is interesting, but for a short course that focuses on the graphics part, modern OpenGL is a better fit imho. If the course focused more on the underlying hardware and ran over a longer period of time, then Vulkan could be a better alternative.

**Comment by 4onen** [comment]
Got it, thanks!
